// => Server Action can still be imported in Client Components
// "use client"

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/N9ZZkm83MKa
 */
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { createProductAction } from "@/actions/createProduct"
import Link from "next/link"

export function ProductCreationForm({ searchParams }: { searchParams: { added?: string } }) {
  return (
    <div className="w-full max-w-md mx-auto">
      <div className="mb-8">
        <h1 className="text-2xl font-bold mb-2">Add Product</h1>
      </div>
      <form className="space-y-4" action={createProductAction} >
        <div className="space-y-2">
          <Label htmlFor="name">Name</Label>
          <Input id="name" name="name" required />
        </div>
        <div className="space-y-2">
          <Label htmlFor="price">Price ($)</Label>
          <Input id="price" name="price" required type="number" />
        </div>
        <Button className="w-full" type="submit">
          Save Changes
        </Button>
        {searchParams.added && <div className="space-y-4">
          <p className="text-green-800">

            Successfully added product &quot;{searchParams.added}&quot;
          </p>
          <p>
            Now check the <Link href="/products" target="_blank">product list</Link>
            {" "}and the <Link href="/" target="_blank">homepage</Link>, they should show your new product.
          </p>
          {process.env.NEXT_PUBLIC_NODE_ENV === "development"
            && <>
              <p className="font-bold">
                You need to run the app in production with
              </p>
              <p className="text-center">
                <code><pre>npm run build && npm run start</pre></code>
              </p>
              <p>
                to observe the impact of revalidation.
              </p>
              <p>
                In development, static pages are always rerendered when you refresh.
              </p>
            </>
          }
        </div>
        }
      </form>
    </div>
  )
}

