/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/fPtLe8Z8uSq
 */
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { ProductList } from "./product-list"
import { routes } from "@/config/routes"

function FLagshipPreorder() {

  return <section className="mb-8">
    <h2 className="text-xl font-bold text-gray-900 dark:text-gray-200 mb-4">Flagship Product</h2>
    <div className="flex bg-white dark:bg-gray-800 shadow rounded-lg p-6">
      <div className="flex-1">
        <img
          alt="Flagship product"
          className="rounded-lg"
          height="250"
          src="/placeholder.svg"
          style={{
            aspectRatio: "250/250",
            objectFit: "cover",
          }}
          width="250"
        />
      </div>
      <div className="flex-1 pl-6">
        <h3 className="text-lg font-bold text-gray-900 dark:text-gray-200 mb-2">Product Title</h3>
        <p className="text-gray-700 dark:text-gray-300 mb-4">$99.99</p>
        <Link href={routes.v1.preorder.href}>
          <Button className="px-6 py-2 bg-blue-500 text-white rounded-lg" variant="default">
            Preorder now
          </Button>
        </Link>
      </div>
    </div>
  </section>
}

export function EcommerceHome() {
  return (
    <div className="flex flex-col min-h-screen bg-gray-100 dark:bg-gray-900">
      <main className="flex-1 p-6">
        <FLagshipPreorder />
        <section>
          <h2 className="text-xl font-bold text-gray-900 dark:text-gray-200 mb-4">All Products</h2>
          <ProductList />
          <div className="text-center">
            <Link
              href={routes.v1.products.href}>
              <Button className="mt-8 mx-auto px-6 py-2 bg-blue-500 text-white rounded-lg" variant="default">
                Click to see more
              </Button>
            </Link>
          </div>
        </section>
      </main>
    </div>
  )
}
